# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_yonetici_ana_menu(object):
    def setupUi(self, yonetici_ana_menu):
        yonetici_ana_menu.setObjectName("yonetici_ana_menu")
        yonetici_ana_menu.resize(800, 600)
        yonetici_ana_menu.setMinimumSize(QtCore.QSize(800, 600))
        yonetici_ana_menu.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(yonetici_ana_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 791, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        yonetici_ana_menu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(yonetici_ana_menu)
        self.statusbar.setObjectName("statusbar")
        yonetici_ana_menu.setStatusBar(self.statusbar)

        self.retranslateUi(yonetici_ana_menu)
        QtCore.QMetaObject.connectSlotsByName(yonetici_ana_menu)

    def retranslateUi(self, yonetici_ana_menu):
        _translate = QtCore.QCoreApplication.translate
        yonetici_ana_menu.setWindowTitle(_translate("yonetici_ana_menu", "Ana Menu"))
        self.pushButton_2.setText(_translate("yonetici_ana_menu", "Kullanıcı / Araç Bilgileri"))
        self.pushButton_3.setText(_translate("yonetici_ana_menu", "Kullanıcı / Araç Bilgileri İşlem"))
        self.pushButton.setText(_translate("yonetici_ana_menu", "Giriş / Çıkış Tabloları"))

        self.pushButton_2.clicked.connect(self.bilgi_tablo_fonksiyon)
        self.pushButton_3.clicked.connect(self.bilgi_islem_tablo)
        self.pushButton.clicked.connect(self.giris_takip)

    def bilgi_tablo_fonksiyon(self):
        os.system("python3 kurumsal_kullanici_tablo.py")

    def bilgi_islem_tablo(self):
        os.system("python3 yonetici_gorev_kurumsal.py")

    def giris_takip(self):
        os.system("python3 yonetici_takip_tablo.py")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    yonetici_ana_menu = QtWidgets.QMainWindow()
    ui = Ui_yonetici_ana_menu()
    ui.setupUi(yonetici_ana_menu)
    yonetici_ana_menu.show()
    sys.exit(app.exec_())
